[[redirects]]
  from = "/signup/account"
  to = "http://49.247.26.149:5100/signup/account"
  status = 200




[[redirects]]
  from = "/member/accounts"
  to = "http://49.247.26.149:5100/member/accounts"
  status = 200



