[[redirects]]
from = "/member/accounts"
status = 200
to = "http://49.247.26.149:5150/member/accounts"

[[redirects]]
from = "/root/post"
status = 200
to = "http://49.247.26.149:5150/root/post"

[[redirects]]
from = "/request/update"
status = 200
to = "http://49.247.26.149:5150/request/update"

