[[redirects]]
  from = "/signup/account"
  to = "http://49.247.26.149:5100/signup/account"
  status = 200




  [[redirects]]
  from = "/post/method"
  to = "http://49.247.26.149:5100/post/method"
  status = 200



